# Generated by Django 5.2.3 on 2025-07-09 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('background', models.TextField()),
                ('discussion', models.TextField()),
                ('standard_min', models.FloatField()),
                ('standard_max', models.FloatField()),
                ('optimal_min', models.FloatField()),
                ('optimal_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BloodTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_id', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('background', models.TextField()),
                ('signs_and_symptoms', models.JSONField()),
                ('differential_diagnoses', models.JSONField()),
                ('causes', models.JSONField()),
                ('diseases', models.JSONField()),
                ('treatment', models.TextField()),
                ('associated_markers_high', models.ManyToManyField(blank=True, related_name='high_conditions', to='bloodapp.marker')),
                ('associated_markers_low', models.ManyToManyField(blank=True, related_name='low_conditions', to='bloodapp.marker')),
            ],
        ),
        migrations.CreateModel(
            name='MarkerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('units', models.CharField(blank=True, max_length=20)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodapp.marker')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='bloodapp.bloodtestreport')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportConditionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('rationale', models.TextField(blank=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodapp.healthcondition')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_suggestions', to='bloodapp.bloodtestreport')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=255)),
                ('response', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('comment', models.TextField(blank=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_responses', to='bloodapp.reportconditionsuggestion')),
            ],
        ),
    ]
