# Generated by Django 5.2.3 on 2025-08-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_patientprofile_current_stage_aianalysisresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcondition',
            name='treatment',
        ),
        migrations.AddField(
            model_name='healthcondition',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcondition',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='healthcondition',
            name='treatments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcondition',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcondition',
            name='causes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcondition',
            name='condition_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='healthcondition',
            name='differential_diagnoses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcondition',
            name='diseases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcondition',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='healthcondition',
            name='signs_and_symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
