# Generated by Django 5.2.3 on 2025-08-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0003_remove_healthcondition_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='clinical_implications_high',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='clinical_implications_low',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='drug_causes_decreased',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='drug_causes_increased',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='drug_tests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='interfering_factors_falsely_decreased',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='interfering_factors_falsely_elevated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='international_unit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='optimal_max_conventional',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='optimal_max_international',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='optimal_min_conventional',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='optimal_min_international',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='other_conditions_high',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='other_conditions_low',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='standard_max_conventional',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='standard_max_international',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='standard_min_conventional',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='standard_min_international',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='standard_unit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
