# Generated by Django 5.2.3 on 2025-08-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0004_marker_clinical_implications_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcondition',
            name='expert_comment_markers',
            field=models.TextField(blank=True, help_text='Expert commentary on which markers are most/least important for risk assessment', null=True),
        ),
    ]
