# Generated by Django 5.2.3 on 2025-08-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0006_patientprofile_blood_analysis_results_and_more'),
        ('bloodapp', '0006_riskcomputationtask'),
    ]

    operations = [
    ]
