version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8080"
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=blooddb
      - DB_USER=postgres
      - DB_PASSWORD=jOHNcENA123!
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - .:/app
    command: ./entrypoint.sh

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=blooddb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jOHNcENA123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
